### ISSUE TITLE
import only works in ts files

### ISSUE THREAD

**Issue by bengreenier** [bengreenier/vscode-node-readme#13]
This is actually a feature, right now. If you take a look at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import you'll notice that no browsers implement `import` yet, and so i've not implemented `js` file support for this syntax.

If this is a feature you'd like to see, simply +1 this issue (it would be extremely easy to expose)

**Comment by jmjpro** [comment]
Chrome developer preview supports modules now. It's time to add this feature! :-)

**Comment by bengreenier** [comment]
Haha agreed! I'll see if I can make some time for this soon. If you're feeling ambitious (and happen to have free time) I'd be more than happy to accept a PR!

**Comment by bengreenier** [comment]
`v1.2.0` is now live on the marketplace and supports `import` in `js` files! 🚀
