### ISSUE TITLE
drop down for package.json

### ISSUE THREAD

**Issue by mclander** [bengreenier/vscode-node-readme#20]
I usually open my project in {$project}/src folder. It exclude Ctrl+Shift+F find in node_modules, fonts in other artefacts.

So  vscode-node-readme cant find package.json (

It could be great if your plugin try to search package.json in parent (or specified folder).

Bets regards, Alex

**Comment by bengreenier** [comment]
@mclander just to be sure i understand, you want to be able to have the module pull up README files for dependencies (like `dependency1` and `dependency2`) in the following situation:

```
project
│
├───node_modules        
│   ├───dependency1     
│   │       package.json
│   │                   
│   └───dependency2     
│           package.json
│                       
└───src                 
        yourcode.js
```

Where `yourcode.js` has:

```
const dep1 = require('dependency1')
const dep2 = require('dependency2')
```

and you right click or `ctrl+shift+r` on either of those require calls, is that correct?

**Comment by mclander** [comment]
Right. Now i found workarround. I open project in root (project dir), and exclude some trash/artefacts directories from vscode visibillity or/and search. In this case your extention works fine.

But i work with multiple projects with difirent trash structures, so setup all of it... I too lazy for). Easy way open main work direcrory (src or app) as root of project.

Could be nice if node-readme can detect these situation and try to find real root of project (suggest by looking for package.json in one or two level up in dir tree).

But i think it minor feature since W/A, Text search in readme could be more great.

Thank for you work. By rules of my company, I have no internet on my workstation, so you make my life easier;)

**Comment by bengreenier** [comment]
@mclander with the new [v2.0.0 release](https://github.com/bengreenier/vscode-node-readme/commit/db6a1c9c7e03adbfb7938fc51278958b41e50961) and [multiroot support in vscode](https://code.visualstudio.com/updates/v1_18#_support-for-multi-root-workspaces) i'm going to close this out because i believe you can leverage those new features to accomplish what you're looking for. Feel free to reopen if you disagree though! 😸
