### ISSUE TITLE
readme vs README filename cross platform issues

### ISSUE THREAD

**Issue by oliversturm** [bengreenier/vscode-node-readme#24]
The extension doesn't seem to work at all for me. For instance, I receive this error message for bluebird (same for others):

```
Unable to open 'Preview bluebird': cannot open npm-data:/bluebird. Detail: Missing registry response data.
```

I can't think of anything special about the project I'm working in. VS Code version is 1.18.0. Any ideas why this would occur?

**Comment by bengreenier** [comment]
Hey @oliversturm! oh no! `1.18.0` introduces some changes to workspaces, and it's possible that's in play (though to be honest, that's not what this failure looks like). That error occurs when the module can't find information about the latest version from npm (see [here](https://github.com/bengreenier/vscode-node-readme/blob/master/src/npmdata.ts#L67)).

I'm shipping [an update](https://github.com/bengreenier/vscode-node-readme/pull/23) that is tested against `1.18.0` (and it's new workspace features) later today, so my advice is let's hold off further investigation until that lands, and if this is still a problem at that point we can dive deeper!

Thanks for taking the time to let me know something is up! hopefully we can get it sorted asap 😸 ⌚️

**Comment by bengreenier** [comment]
@oliversturm - that update is live, can you try updating and let me know if that fixed the issue?

If not i'm curious if:

1) you have internet connectivity on the machine you're testing on
2) you have a workspace open (a [collection of multiple folders](https://code.visualstudio.com/docs/editor/multi-root-workspaces))
3) you have a folder open (a single directory,  File -> Open Folder)
4) you have bluebird locally under `<anyFolderOpenInWorkspace>\node_modules\bluebird` 

Thanks for again for helping me work through this potential issue! 🥇

**Comment by oliversturm** [comment]
Thanks for your response. After the update, the version showing in VS Code is now v2.1.0, but the problem persists - I still see the same error message for bluebird and seemless-immutable. I have found one more detail: when I try to see the readme for `@google-cloud/datastore`, I see a different error "cannot open node-readme-npm-data:/%40google-cloud/datastore. Detail: Invalid statusCode 404."

(I checked to be sure, and both `seamless-immutable` and `@google-cloud/datastore` include a README.md that I can open by finding it in the Explorer panel.)

To answer your questions:

1. Yes, I have an internet connection. the machine is the same I'm writing this comment on right now. 
2. I have not opened a workspace
3. I started code using `code .` in my project working directory. I would assume that results in the same state as File -> Open Folder.
4. bluebird and the other packages I was trying are local in `node_modules\<package>` right there in the project folder.

**Comment by oliversturm** [comment]
Okay, it seems I found the problem. In three places in [this part of extension.ts](https://github.com/bengreenier/vscode-node-readme/blob/master/src/extension.ts#L77-L86) you refer to a file `readme.md`. That's not the name of the readme files - they are called `README.md`. I'm on Linux, this makes an important difference.

I changed the names to `README.md` and I was able to bring up the bluebird readme correctly.

**Comment by bengreenier** [comment]
ah, right. I hadn't had a chance to test this on anything other than windows - that makes sense. I'll work on a fix sometime this week (or I'd love to accept a PR that makes this lookup work cross platform, if you have time to work on one).

As for the `@google-cloud/datastore` one, i've not tested that format, it's very possible that some of the path handling doesn't deal with that appropriately. I've added #25 to take a look at ensuring that all works as expected.

Thanks for following up here - folks that take the time to file and follow through with these things are the reason plugins like this can be successful! 💯

**Comment by oliversturm** [comment]
I didn't do loads of detailed testing, but with the change of the `readme.md` to `README.md`, the problem seemed to be fixed on my machine. I didn't create a PR because I really didn't change anything else and my Prettier setup messed up your file formatting quite a bit :)
