### ISSUE TITLE
issue with forward-slashes in module names

### ISSUE THREAD

**Issue by bengreenier** [bengreenier/vscode-node-readme#25]
From [here](https://github.com/bengreenier/vscode-node-readme/issues/24#issuecomment-347122517): 

I have found one more detail: when I try to see the readme for @google-cloud/datastore, I see a different error "cannot open node-readme-npm-data:/%40google-cloud/datastore. Detail: Invalid statusCode 404."

**Comment by bengreenier** [comment]
Even if this isn't an issue, it isn't currently tested and we should test and verify that this works as expected

**Comment by oliversturm** [comment]
I can confirm that this is an issue at the moment. With the `README.md` fix from #24 in place, I see error messages for a path `<projectdir>/node_modules/@google-cloud/datastore/README.md/@google-cloud` - obviously that path is mangled.

**Comment by bengreenier** [comment]
just to capture this information here...

for `@google-cloud/datastore` the expected local path is `<projectdir>/node_modules/@google-cloud/datastore/README.md` while the expected npm registry api lookup is `https://registry.npmjs.org/@google-cloud%2fdatastore`.
