### ISSUE TITLE
Missing registry response data

### ISSUE THREAD

**Issue by CallMeLaNN** [bengreenier/vscode-node-readme#29]
I just got this error on latest vscode v1.19.2:

    Unable to open 'Preview express': cannot open node-readme-npm-data:/express. Detail: Missing registry response data.

It does not work anymore even after restart the vscode and reinstall this extension.

**Comment by bengreenier** [comment]
Hey @CallMeLaNN thanks for raising this issue! This error occurs when we can't find the module readme on your local machine (in this case, it can't find `./node_modules/express/README.md`), and we try to connect to npm to get the data from there. Looks like something is up either with the communication code with the npm registry, or your network connection.

I'll start looking into the code, and try to get a repro going locally, in the meantime can you confirm the following?

+ You do not have `node_modules\express\README.md` locally
+ You have a network connection
+ you can access [`https://registry.npmjs.org`](https://registry.npmjs.org) via a browser (expect a 200 status code with some json content)

**Comment by bengreenier** [comment]
@CallMeLaNN I found a bug that may be causing this 😞 

If you have something in `package.json` like `"express": "^4.13.4"` the npm query will fail, because i'm mistakenly trying to match the string literal `^4.13.4` to a version, which naturally doesn't work. There's two fixes I'm working on that will help with that case:

+ fallback to latest version when the string literal match fails
+ parse string literal as semver and actual semver match against these versions

__can you plase confirm for me if this sounds like what you're experiencing?__

**Comment by CallMeLaNN** [comment]
I'll get back to you by end of day. What I can tell you now is not only 'express' but it can't find all other modules also.

**Comment by CallMeLaNN** [comment]
Ahah. `.yarnclean` file exist and somehow it remove all `*.md` files even though I am not calling `yarn autoclean`. I just recreate `node_modules` and trying to play around with the existence of the `README.md` file and the existence of caret ranges `^` in `package.json`.

Now I know, it trying to find the `README.md` locally first, then fetch on npm registry based on the version and yes you need to match the version range instead of just string literal to fix the error.

Now I can view readme file from my local anyway.

**Comment by bengreenier** [comment]
Cool thanks for clarifying that stuff @CallMeLaNN - i'm glad you got it working with local markdown! 

I'm going to close this out and link an issue for resolving the semver issues! thanks again for flagging this, you helped me find the semver bug which will be great to get fixed! 🚀 👍
